### ISSUE TITLE
Team - keine user_id

### ISSUE THREAD

**Issue by sebk** [sebk/league#1]
Bei der Abfrage aller Teams eines Users (zB current_user.teams.all) besitzen die Teams keine user_id (?)

**Comment by romanblick** [comment]
Wenn dann haben doch die teammemberships eine user_id. oder wie darf ich deine Frage verstehen?

**Comment by sebk** [comment]
ah ok. stimmt, dann gehts ja darüber.
hatte mich nur gewundert, dass in der team-tabelle zwar ein feld user_id steht, das feld allerdings nicht gefüllt ist.

**Comment by romanblick** [comment]
ich hab das gestern gesäubert. Du hast die vermutlich den aktuellen Code geholt, aber noch nicht alle migrations gefahren - daher ist das feld noch in der teams-tabelle drin. Sollte weg sein, wenn du die Migrations gefahren hast.

Siehe db/migrate/20110624224253_remove_unneccessary_fields_from_user_and_team.rb

**Comment by sebk** [comment]
ok alles klar
